version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: learn-go-api-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - target: 5432
        published: 5434
        protocol: tcp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - learn-go-api-network

volumes:
  postgres_data:
    driver: local

networks:
  learn-go-api-network:
    driver: bridge